"""Pydantic schemas — graph state, agent I/O, scenarios.

LOCKED Weekend 1 schemas. Agent code is written against these; if a schema
feels wrong while building an agent, revise it HERE first, then continue.

Key design decisions
--------------------
* WeaknessModel is updated by a deterministic reducer (see the Coach node),
  never regenerated by an LLM. ``CategoryStat`` keeps a single source of
  truth — ``confidence_log`` — and exposes ``seen`` / ``caught`` / rates as
  computed views, so the running model cannot silently drift.
* ``AttackCategory`` defines all six roadmap categories up front. Weekend 1
  only *exercises* the three in ``WEEKEND_1_CATEGORIES`` (enforced by the
  Author prompt, not the type), so Weekend 2 changes prompts — not this file.
* Reveal-only fields — ``Tell``, ``ArtifactGen.targeting_rationale``,
  ``.is_phish``, ``.tells``, ``.category``, ``.difficulty`` — must never be
  rendered to the learner before they answer. Only artifact_type / sender /
  subject / body are learner-facing.
"""

from __future__ import annotations

from collections.abc import Iterable
from enum import StrEnum
from typing import Annotated, Literal

from pydantic import (
    BaseModel,
    BeforeValidator,
    ConfigDict,
    Field,
    computed_field,
    model_validator,
)

# --- Shared string helpers ------------------------------------------------


def _strip(value: object) -> object:
    """Trim whitespace from strings; pass non-strings through to type validation."""
    return value.strip() if isinstance(value, str) else value


Stripped = Annotated[str, BeforeValidator(_strip)]
"""A string with surrounding whitespace trimmed before validation runs."""

ShortText = Annotated[str, BeforeValidator(_strip), Field(min_length=1, max_length=400)]
"""A trimmed, non-empty single-line string — used for list items (phrases, spans)."""


# --- Attack taxonomy ------------------------------------------------------


class AttackCategory(StrEnum):
    """A phishing tactic. The Coach tags each round with one to map blind spots."""

    # Weekend 1 — exercised now (see WEEKEND_1_CATEGORIES).
    AUTHORITY_IMPERSONATION = "authority_impersonation"
    URGENCY_SCARCITY = "urgency_scarcity"
    LOOKALIKE_DOMAIN = "lookalike_domain"
    # Weekend 2+ — defined now so this locked file never changes just to add them.
    PRETEXTING = "pretexting"
    OAUTH_CONSENT = "oauth_consent"
    TRUST_STACK_ABUSE = "trust_stack_abuse"


WEEKEND_1_CATEGORIES: frozenset[AttackCategory] = frozenset(
    {
        AttackCategory.AUTHORITY_IMPERSONATION,
        AttackCategory.URGENCY_SCARCITY,
        AttackCategory.LOOKALIKE_DOMAIN,
    }
)
"""The three categories the Author is allowed to use in Weekend 1."""


# --- Persona --------------------------------------------------------------


class PersonaProfile(BaseModel):
    """Learner's role-played persona. A session-scoped fiction — no real PII.

    Weekend 1 stores the learner's free-text self-description verbatim and lets
    the Author interpret it each round. Structured parsing is deferred.
    """

    model_config = ConfigDict(extra="forbid")

    raw_description: Stripped = Field(
        min_length=3,
        max_length=500,
        description=(
            "Verbatim persona text from the learner, e.g. "
            "'CS undergrad at a fictional university'."
        ),
    )


# --- Weakness model -------------------------------------------------------

_EXPLORATION_PRIOR = 0.5
"""weakness_score for a not-yet-seen category — high enough to get it explored."""

_OVERCONFIDENCE_WEIGHT = 0.5
"""How much a confident-but-wrong history adds to a category's weakness_score."""


class ConfidenceEntry(BaseModel):
    """One round's outcome for a category: how sure the learner was, and whether
    they were right. The atom the WeaknessModel is built from."""

    model_config = ConfigDict(extra="forbid")

    confidence: int = Field(ge=1, le=5, description="Learner's stated confidence, 1-5.")
    correct: bool = Field(description="Whether the learner's verdict matched ground truth.")


class CategoryStat(BaseModel):
    """Per-category detection record. ``confidence_log`` is the single source of
    truth; every other number here is a computed view of it.

    No ``extra="forbid"`` here: ``model_dump()`` emits the computed fields, and
    re-validating that dump (LangGraph checkpoint round-trip) must not reject
    them as unexpected keys.
    """

    confidence_log: list[ConfidenceEntry] = Field(default_factory=list)

    @computed_field  # type: ignore[prop-decorator]
    @property
    def seen(self) -> int:
        """Rounds in which this category was presented."""
        return len(self.confidence_log)

    @computed_field  # type: ignore[prop-decorator]
    @property
    def caught(self) -> int:
        """Rounds the learner judged correctly."""
        return sum(1 for entry in self.confidence_log if entry.correct)

    @computed_field  # type: ignore[prop-decorator]
    @property
    def missed(self) -> int:
        """Rounds the learner judged wrongly."""
        return self.seen - self.caught

    @computed_field  # type: ignore[prop-decorator]
    @property
    def catch_rate(self) -> float:
        """Fraction caught, 0.0 .. 1.0 (0.0 if never seen)."""
        return self.caught / self.seen if self.seen else 0.0

    @computed_field  # type: ignore[prop-decorator]
    @property
    def mean_confidence_when_wrong(self) -> float | None:
        """Average stated confidence on wrong answers — the overconfidence signal.
        None if the learner has never been wrong in this category."""
        wrong = [entry.confidence for entry in self.confidence_log if not entry.correct]
        return sum(wrong) / len(wrong) if wrong else None

    @computed_field  # type: ignore[prop-decorator]
    @property
    def weakness_score(self) -> float:
        """How strongly the Author should target this category. Higher = weaker.

        Combines miss rate with an overconfidence penalty — being wrong *and*
        confident is the worst case. An unseen category returns a fixed prior
        so it gets explored before a seen-but-weak category is over-drilled.
        """
        if self.seen == 0:
            return _EXPLORATION_PRIOR
        miss_rate = 1.0 - self.catch_rate
        mcw = self.mean_confidence_when_wrong
        overconfidence = 0.0 if mcw is None else (mcw - 1.0) / 4.0
        return round(miss_rate + _OVERCONFIDENCE_WEIGHT * overconfidence, 4)


class WeaknessModel(BaseModel):
    """Per-learner detection-skill map across all categories. Lives in graph
    state; updated each round by the Coach node's deterministic reducer.

    No ``extra="forbid"`` — same computed-field round-trip reason as CategoryStat.
    """

    stats: dict[AttackCategory, CategoryStat] = Field(
        default_factory=lambda: {category: CategoryStat() for category in AttackCategory}
    )

    @model_validator(mode="after")
    def _ensure_every_category(self) -> WeaknessModel:
        """Guarantee every category has a stat, so ``stats[c]`` is always safe —
        even for a model loaded from an older or partial checkpoint."""
        for category in AttackCategory:
            self.stats.setdefault(category, CategoryStat())
        return self

    @computed_field  # type: ignore[prop-decorator]
    @property
    def total_rounds(self) -> int:
        """Total rounds recorded across all categories."""
        return sum(stat.seen for stat in self.stats.values())

    def weakest_category(self, candidates: Iterable[AttackCategory]) -> AttackCategory:
        """Return the candidate category with the highest weakness_score.

        Ties break toward the earlier ``AttackCategory`` member, so selection is
        deterministic and reproducible. ``candidates`` must be non-empty — the
        graph passes ``WEEKEND_1_CATEGORIES`` so out-of-scope categories are
        never selected.
        """
        ordered = list(candidates)
        if not ordered:
            raise ValueError("weakest_category() needs at least one candidate")
        position = {category: i for i, category in enumerate(AttackCategory)}
        return max(
            ordered,
            key=lambda category: (self.stats[category].weakness_score, -position[category]),
        )


# --- Artifact generation --------------------------------------------------


class Tell(BaseModel):
    """A specific red flag planted in an artifact. Reveal-only — never shown to
    the learner until the Coach's post-round reveal."""

    model_config = ConfigDict(extra="forbid")

    category: AttackCategory = Field(description="Which tactic this tell belongs to.")
    marker: Stripped = Field(
        min_length=1,
        max_length=400,
        description=(
            "The exact span or element in the artifact that gives it away — "
            "e.g. the lookalike domain or the urgency phrase — quoted verbatim."
        ),
    )
    explanation: Stripped = Field(
        min_length=1,
        max_length=2000,
        description="Why this is a red flag and what the learner should take away.",
    )


ArtifactType = Literal["email", "sms", "dm", "oauth_screen"]


class ArtifactGen(BaseModel):
    """What the Phishing Author produces each round.

    Learner-facing fields: ``artifact_type``, ``sender``, ``subject``, ``body``.
    Everything else is reveal-only and must be withheld until the learner has
    answered.
    """

    model_config = ConfigDict(extra="forbid")

    artifact_type: ArtifactType = Field(
        description="Channel of the artifact. Weekend 1 uses email / sms / dm."
    )
    category: AttackCategory = Field(
        description="The primary tactic this round trains and measures."
    )
    is_phish: bool = Field(
        default=True,
        description=(
            "Ground truth. Weekend 1 artifacts are always phishing (True); "
            "legitimate decoys arrive in Weekend 2."
        ),
    )
    sender: Stripped = Field(
        min_length=1,
        max_length=400,
        description="Display name and address / number / handle of the apparent sender.",
    )
    subject: Stripped | None = Field(
        default=None,
        max_length=400,
        description="Subject line. Required for email; omitted for every other type.",
    )
    body: Stripped = Field(
        min_length=1,
        max_length=8000,
        description="The artifact's full content, exactly as the learner would see it.",
    )
    tells: list[Tell] = Field(
        default_factory=list,
        max_length=12,
        description="Red flags planted in the artifact. Non-empty when is_phish is True.",
    )
    difficulty: int = Field(
        ge=1,
        le=5,
        description="Author's self-rated difficulty, 1 (obvious) to 5 (subtle).",
    )
    targeting_rationale: Stripped = Field(
        min_length=1,
        max_length=2000,
        description=(
            "Author's private note on which weakness this round targets and how. "
            "Reveal-only — never shown to the learner."
        ),
    )

    @model_validator(mode="after")
    def _check_consistency(self) -> ArtifactGen:
        if self.subject == "":
            self.subject = None
        if self.artifact_type == "email" and not self.subject:
            raise ValueError("email artifacts require a subject")
        if self.artifact_type != "email" and self.subject is not None:
            raise ValueError(f"{self.artifact_type} artifacts must not have a subject")
        if self.is_phish and not self.tells:
            raise ValueError("a phishing artifact must plant at least one tell")
        if not self.is_phish and self.tells:
            raise ValueError("a legitimate artifact must not carry tells")
        return self


# --- Student response & coach analysis ------------------------------------


class StudentResponse(BaseModel):
    """The learner's verdict on one artifact."""

    model_config = ConfigDict(extra="forbid")

    verdict: Literal["phish", "legit"] = Field(
        description="The learner's call on the artifact."
    )
    confidence: int = Field(ge=1, le=5, description="How sure the learner is, 1-5.")
    reasoning: Stripped = Field(
        min_length=1,
        max_length=8000,
        description="The learner's explanation of their verdict.",
    )
    flagged_tells: list[ShortText] = Field(
        default_factory=list,
        max_length=20,
        description="Spans the learner explicitly called out as suspicious.",
    )


class CoachAnalysis(BaseModel):
    """The Coach's pedagogical output for one round, stored in RoundResult.

    ``student_correct`` is set deterministically by the Coach node (ground
    truth vs. verdict) — it is NOT emitted by the LLM. The remaining fields are
    the Coach LLM's teaching output. The running WeaknessModel is updated by a
    separate deterministic reducer; the LLM never regenerates it.
    """

    model_config = ConfigDict(extra="forbid")

    student_correct: bool = Field(
        description=(
            "Whether the learner's verdict matched ground truth. "
            "Computed by the Coach node, not emitted by the LLM."
        )
    )
    missed_tells: list[Tell] = Field(
        default_factory=list,
        max_length=12,
        description="Planted tells the learner failed to identify.",
    )
    reasoning_strengths: list[ShortText] = Field(
        default_factory=list,
        max_length=10,
        description="What the learner's reasoning got right.",
    )
    reasoning_weaknesses: list[ShortText] = Field(
        default_factory=list,
        max_length=10,
        description="Weak or unsound moves in the learner's reasoning.",
    )
    coaching_message: Stripped = Field(
        min_length=1,
        max_length=8000,
        description=(
            "The reveal shown to the learner — what the tells were, what their "
            "reasoning got right and wrong, and what to watch for next time."
        ),
    )


# --- Round & session ------------------------------------------------------


class RoundResult(BaseModel):
    """A completed round, appended to the session history.

    ``response`` and ``coach_analysis`` stay optional so a round can be recorded
    while still in flight, but a finished round has both populated.
    """

    model_config = ConfigDict(extra="forbid")

    round_num: int = Field(ge=1, description="1-based round index.")
    artifact: ArtifactGen
    response: StudentResponse | None = None
    coach_analysis: CoachAnalysis | None = None


class SessionState(BaseModel):
    """LangGraph graph state. Persisted in the SQLite checkpointer between rounds
    and across the human-in-the-loop interrupt.

    No ``extra="forbid"`` — leave room for LangGraph-managed internals.

    Round lifecycle: ``round_num`` counts *completed* rounds. The Author
    generates round ``round_num + 1`` into ``current_artifact``; the Coach,
    after analysing it, appends a RoundResult, clears the current_* fields, and
    increments ``round_num``.
    """

    student_persona: PersonaProfile
    weakness_model: WeaknessModel = Field(default_factory=WeaknessModel)
    round_history: list[RoundResult] = Field(default_factory=list)
    current_artifact: ArtifactGen | None = None
    current_response: StudentResponse | None = None
    round_num: int = Field(default=0, ge=0, description="Completed rounds so far.")
    max_rounds: int = Field(default=8, ge=1)
